#!/bin/bash
awk '
/const updateVariant/ {
    print "  const generateVariants = (options: {name: string, values: string[], inputValue: string}[]) => {"
    print "    const validOptions = options.filter(o => o.name.trim() && o.values.length > 0);"
    print "    if (validOptions.length === 0) {"
    print "      if (options.length === 0) setVariants([]);"
    print "      return;"
    print "    }"
    print "    const generateCombinations = (opts: any[], idx = 0, current = {}): any[] => {"
    print "      if (idx === opts.length) return [current];"
    print "      const opt = opts[idx];"
    print "      let combos: any[] = [];"
    print "      for (const val of opt.values) {"
    print "        combos = combos.concat(generateCombinations(opts, idx + 1, { ...current, [opt.name]: val }));"
    print "      }"
    print "      return combos;"
    print "    };"
    print "    const combinations = generateCombinations(validOptions);"
    print "    const baseSku = formData.sku || \"SKU\";"
    print "    const newVariants = combinations.map(combo => {"
    print "      const existing = variants.find(v => JSON.stringify(v.attributes) === JSON.stringify(combo));"
    print "      const tagSuffix = Object.values(combo).map((v: any) => v.replace(/\\s+/g, \"\").toUpperCase()).join(\"-\");"
    print "      return existing || {"
    print "        sku: `${baseSku}-${tagSuffix}`,"
    print "        price_modifier: 0,"
    print "        inventory_count: 0,"
    print "        attributes: combo"
    print "      };"
    print "    });"
    print "    setVariants(newVariants);"
    print "  };"
    print ""
    print "  const addOption = () => setProductOptions([...productOptions, { name: \"\", values: [], inputValue: \"\" }]);"
    print "  const updateOption = (index: number, field: string, value: any) => {"
    print "    const newOptions = [...productOptions];"
    print "    (newOptions[index] as any)[field] = value;"
    print "    setProductOptions(newOptions);"
    print "    if (field !== \"inputValue\") generateVariants(newOptions);"
    print "  };"
    print "  const removeOption = (index: number) => {"
    print "    const newOptions = productOptions.filter((_, i) => i !== index);"
    print "    setProductOptions(newOptions);"
    print "    generateVariants(newOptions);"
    print "  };"
    print "  const handleOptionKeyDown = (e: React.KeyboardEvent, index: number) => {"
    print "    if (e.key === \"Enter\" || e.key === \",\") {"
    print "      e.preventDefault();"
    print "      const val = productOptions[index].inputValue.trim();"
    print "      if (val && !productOptions[index].values.includes(val)) {"
    print "        const newOptions = [...productOptions];"
    print "        newOptions[index].values.push(val);"
    print "        newOptions[index].inputValue = \"\";"
    print "        setProductOptions(newOptions);"
    print "        generateVariants(newOptions);"
    print "      }"
    print "    }"
    print "  };"
    print "  const removeOptionValue = (optIndex: number, valIndex: number) => {"
    print "    const newOptions = [...productOptions];"
    print "    newOptions[optIndex].values = newOptions[optIndex].values.filter((_, i) => i !== valIndex);"
    print "    setProductOptions(newOptions);"
    print "    generateVariants(newOptions);"
    print "  };"
    print ""
    print "  const applyBulkVariant = (field: string, value: string | number) => {"
    print "    setVariants(variants.map(v => ({ ...v, [field]: value })));"
    print "  };"
    print $0
    next
}
{print}
' src/pages/admin/AddProduct.tsx > temp.tsx && mv temp.tsx src/pages/admin/AddProduct.tsx
